apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-mirror-secrets
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-vault
    kind: ClusterSecretStore
  target:
    name: gitea-mirror-secrets
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: origin-ca-issuer/localfloof
      property: api-token
