apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-mirror-github-app-token
  namespace: argo
spec:
  refreshInterval: "30m"
  target:
    name: gitea-mirror-github-app-token
    creationPolicy: Owner
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: GithubAccessToken
        name: github-app-auth-token
