apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gitea-mirror
  namespace: argo
spec:
  templates:
    - name: sync
      container:
        image: ghcr.io/96daysleft/gitea-mirror:latest
        command: ["python", "main.py"]
        args: ["sync"]
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitea-mirror-secrets
                key: github_token
          - name: GITEA_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitea-mirror-secrets
                key: gitea_token
          - name: GITHUB_ORG
            value: "96daysleft"
          - name: GITEA_URL
            value: "https://gitea.localfloof.com"
          - name: GITEA_ORG
            value: "96daysleft"
          - name: MIRROR_INTERVAL
            value: "8h"

    - name: update-pat
      container:
        image: ghcr.io/96daysleft/gitea-mirror:latest
        command: ["python", "main.py"]
        args: ["update-pat"]
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitea-mirror-secrets
                key: github_token
          - name: GITEA_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitea-mirror-secrets
                key: gitea_token
          - name: GITEA_URL
            value: "https://gitea.localfloof.com"
          - name: GITEA_ORG
            value: "96daysleft"
          - name: MIRROR_INTERVAL
            value: "8h"
