name: Main branch check

on:
  push:
    branches: [main]

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  main-check:
    uses: 96daysleft/github-workflows/.github/workflows/python-pr-check.yml@release
    with: 
      pytest-args: "-q"
      run-pr-agent:  false
